### ISSUE TITLE
Negative retention time numbers?

### ISSUE THREAD

**Issue by PatrickvanZalm** [grosenberger/easypqp#81]
Hi,

We noticed that there is a small percentage of peptides with a negative retention time, any idea what that could be / mean?

With kind regards,
Patrick

**Comment by grosenberger** [comment]
Hi Patrick,

If you used the internal RT calibration, the range will be set from 0 - 100 for the reference run. However, if you combine multiple runs, one or several of those might have identified peptides that elute earlier than the earliest peptide of the reference run. In that case, the values will be negative. The majority of the DIA analysis tools can account for that, since also the Biognosys iRT kit has negative values.

Hope that helps!

Best regards,
George
