### ISSUE TITLE
Transitions with the same PrecursorMz and different annotations

### ISSUE THREAD

**Issue by jcharkow** [grosenberger/easypqp#95]
Although rare, I found that with large libraries there can be the case where transitions can have different annotations and the same ProductMz. Currently these are listed as different transitions however I don't know if this is the ideal behaviour because DIA analysis software could assume that two different transitions have a perfect correlation with one another when in fact it is just the same transition. 

Also when creating a library from fractionated runs we might have the two different annotations with the same m/z having slightly different library intensity values.

#### Example: 
![image](https://user-images.githubusercontent.com/47336288/220753570-ceebcf9a-e66b-4ac6-897f-12dea9ba3ee2.png)

These are the transitions for one of the peptide precursors. Note that here the `b5^1` ion and the `b10^2` ion have the same ProductMz but different library intensities. 

Looking at the corresponding .peakpkl files (a snippet is shown in the dataframe below), we can see that these specific entries come from different fractions (based on the intensity values). However there are some fractions which have both a `b5^1` and a `b10^2` ion (e.g. `Hela_50ug_HpH_F5_S1-A5_1_4468.peakpkl`).  
![image](https://user-images.githubusercontent.com/47336288/220754157-77be186f-959a-410a-882d-14bce10630d6.png)

#### Background On Example 
This library was generated from HeLa fractionation on the timsTOF. DDA analysis was run using fragpipe and easypqp was on command line with the following command. 

`easypqp convert --pepxml interact-XXX.pep.xml --spectra XXX_uncalibrated.mgf --exclude-range -1.5,3.5 --psms XXX.psmpkl --peaks XXX.peakpkl` 

#### Possible Solution 
I'm not sure what the best way to address this, I was thinking that if ProductMz are within a certain PPM of one another (or exactly the same) than only the ProductMz of the lowest charge state should be reported. Possibly this should be addressed here or possibly part of the pyopenms theoretical isotope generator, I'm not sure.

**Comment by chris-discopharma** [comment]
We are observing similar behaviour. When we run easyPQP twice on the same inputs, there are around 30 fragments or so that have similar differential naming behaviour. Almost always, as with the cases above, the charge state value and the series index number value both seem to double. 

[differences_2runs_easyPQP_withannotation.txt](https://github.com/grosenberger/easypqp/files/11879311/differences_2runs_easyPQP_withannotation.txt)

I attach a diff output from two easyPQP runs. After manually checking a handful of cases in this file, I am convinced that the variable identifications are not incorrect - the unique IDs to each run make sense with respect to the original peptide sequence. 

Rather, the concern is that the outputs of easyPQP are non-deterministic, and thus contribute a bit of noise to the outputs of any DIA quantification that depends on easyPQP.

**Comment by guoci** [comment]
You can consider fixing `PYTHONHASHSEED` to determine if the problem originates from a random  `PYTHONHASHSEED`.
https://docs.python.org/3/using/cmdline.html#envvar-PYTHONHASHSEED

**Comment by grosenberger** [comment]
Thanks for reporting the issue. I tried to resolve this in the PR above.

**Comment by chris-discopharma** [comment]
Hi George, thanks a lot for the update! Just to clarify, which parameter would be required for the precision setting?

**Comment by grosenberger** [comment]
You can set this during conversion with: `easypqp convert --precision_digits=6`. I have not tested this and the effects of different parameters to a wide extent. In the one example of a timsTOF run that I tried, it removed just 3 transitions. I believe the effects will be very mild on protein-level, but it's of course cleaner now.

It would be great to hear if it works for you or if you encounter any other issues.
